### ISSUE TITLE
wrong form validations

### ISSUE THREAD

**Issue by fazibear** [apotonick/reform#186]
When I invoke a `valid?` method directly on `Reform::Contract` it will return `true` and clear all errors.
This is bad, it makes a form valid. This is proper behavior ?

**Comment by apotonick** [comment]
The `valid?` method is not documented and not part of Reform's API. What you want is `Contract#validate` which returns the validity.

`#valid?` should be made private, good point, man! It is imported from `ActiveModel::Validations` but, as I said, not part of our public API. Do you want to privatise it in a PR? Thanks! :beers:

**Comment by fazibear** [comment]
So I should use `errors.empty?` or `errors.valid?`. But it it makes more sense to check if `errors` are `empty`, and check if `form` is `valid?`. `errors.valid?` looks scary.

**Comment by apotonick** [comment]
You need to save the result from the `result = validate(params)` call. The API is designed to be as stateless and as functional as possible. Less instance variables (e.g. whether or not the form is valid) result in less sources for errors.

I find the API that `ActiveModel::Validations` provides wrong - it is a classy source or errors since you "confused" the order of methods, whereas Reform simply exposes one single method to validate and return the result.
