### ISSUE TITLE
how to combine form errors and model errors?

### ISSUE THREAD

**Issue by novokshonovi** [apotonick/reform#219]
I have different validations in form object and in model, therefore I can have errors either in model or in form, or in both of them. How can I combine these errors?

**Comment by freemanoid** [comment]
As I understand, in reform you have only form errors. If you want to combine some custom validations (form specific) and AR model validation, you need to use [copy_validations_from](https://github.com/apotonick/reform#validations-from-models) along with custom validations.

**Comment by novokshonovi** [comment]
It does not work for me, I am using refile and it is not using model validators, however it generates errors objects for model if attached image has invalid content type

**Comment by freemanoid** [comment]
I believe you should somehow map refile validations to reform form class then.

**Comment by apotonick** [comment]
Yeah, the refile validations should be in the form. I am guessing the refile validators are not copied properly when using `copy_validations_from`. This is not Reform's fault, though!

@novokshonovi Can you paste the code where/how you define the refile validations? I have never used that gem. Alternatively, this works great for me: https://github.com/musaffa/file_validators

**Comment by novokshonovi** [comment]
class User < ActiveRecord::Base
  attachment :profile_image, content_type: "image/jpeg"  
end

and form has profile_image property, in form I have no additional validations. If image has different from "image/jpeg" content type form.save fails but form.errors is empty. In this example user.errors will hold the errors of attached image

**Comment by apotonick** [comment]
Yeah, got it, thanks!

Please use https://github.com/musaffa/file_validators it will make your life easier as you don't have to put validations into the model, but form.

**Comment by musaffa** [comment]
@novokshonovi @apotonick Refile sends json string as the value of the file after form submission. So [file validator](https://github.com/musaffa/file_validators) cannot detect the size nor can it detect the content type based on its the content as the file itself is missing. But it could use size and content type values passed along with the json string. To support this, I've updated the `file validator` gem.

Now you can add this for your form object:
```ruby
validates :profile_image, file_size: { less_than_or_equal_to: 1.megabyte },
                          file_content_type: { allow: 'image/jpeg' }
```
And it will work just fine with all refile associated forms. Cheers!

As of version 2, file validator will not try to detect media type spoofing by default. To enable this security feature, you need to add `mode: :strict` option in the content type validator. Note, `mode: :strict` wont work with direct image uploading system like refile, carrierwave direct etc. I think it is the job of those direct file uploaders themselves to check for media type spoofing. I'm a big fan of Refile and I hope I can submit a PR for media type spoof detection at its library core.

We can still use file validator in the form objects rather than cluttering models with validations.

**Comment by fran-worley** [comment]
I'm going to close this as its been nearly a year and we've got some valid solutions here. Any update @novokshonovi ? Do reopen if you need. 😄
