### ISSUE TITLE
Nested forms, n to 1

### ISSUE THREAD

**Issue by afbroman** [apotonick/reform#225]
I’m having trouble creating a form object that works for an n to 1 relationship. In my project, a `Participant` has many `Visits`, but the form object is for creating and editing a `Visit`, selecting the participant’s `adrc_id` in the form to create the association.

The form object works for the `new` form with this property, but creates a new participant each time with the same `adrc_id`:

```
property :participant do
  property :adrc_id
end
```

Adding coercion via Virtus to coerce into the correct participant doesn’t work with the following nested `adrc_id` field.

```
class CurrentParticipant < Virtus::Attribute
  def coerce(value)
    Participant.find_by(adrc_id: value[:adrc_id])
  end
end

property :participant, type: CurrentParticipant do
  property :adrc_id, validates: { presence: true, adrc_id: true }
end
```

I thus removed the `property :adrc_id` line, which works perfectly for the `new` form, but in the `edit` form it now doesn’t pull in the `adrc_id` for the visit’s participant:

```
property :participant, type: CurrentParticipant
```

I have a feeling I’m just missing something obvious. I need to coerce the adrc_id into the full participant for the `new` form, but go the other direction for the `edit` form.

Any suggestions, or a pointer to documentation in the Trailblazer book?

Thanks,
Andrew

**Comment by apotonick** [comment]
Hey Andrew,

please don't use coercion for complex type conversions. This was only meant to implement Date conversions and the like.

I think what you need is a populator to setup the form. Pg. 90 "Pre-populating Forms" and Pg. 93 "Populating Forms For Validation".

The section describe how populate a nested property in case it's empty. In chapter 7 we will learn how to do that dynamically.

I'm sorry to limit my information flow, but I'm not sure I understand your problem: So, everything is fine for `Form.new`, and then things need to get fixed in `form.validate`?

Here's some more docs, for Reform 2, though: http://trailblazerb.org/gems/reform/populators.html

Let me know if you can't make it work, man!

**Comment by afbroman** [comment]
Thank you for your quick response, Nick, and your great pointers. I’ll dig into the references immediately.
