### ISSUE TITLE
Simple form treat all fields as 'required'

### ISSUE THREAD

**Issue by AdrianNowik** [apotonick/reform#245]
Hello, after update to version 2.0.0 something strange happened in my forms. Now simple form is treating all inputs as required, validation is still working as it should, but in my form, every field has required mark. Downgrading to version 1.2.6 helped, any idea what is wrong ?

**Comment by jumichot** [comment]
Same problem here ;)

**Comment by apotonick** [comment]
Did you include `Reform::Form::ActiveModel::ModelReflections`?

**Comment by FelipeKoblinger** [comment]
Same problem here. The problem started on v2.0.0.rc2 (v2.0.0.rc1 works), I think it was something related to "start cleaning up Errors." commit (ad71fee83117ccd4aa5390b76d6dbae62a7b96bc). It also broke Client Side Validations gem.

**Comment by apotonick** [comment]
Yeah, i completely extracted the AM-related validations logic, it is no longer mixed into Reform::Form itself, but a composite object.

Simple_form and client-side-validations don't follow any interface and do lots of `respond_to?` on the "model" (which is a form object), and that fails now. Maybe it's a good time to fix that in the respective gems now, as I won't go back to including AM::Validations into the form.

**Comment by apotonick** [comment]
Oh, and BTW, I'm 100% sure that @rafaelfranca and the Simpleform team are happy to work out a better interface here.

**Comment by niedhui** [comment]
This is because simple_form rely on `validators_on` methods to test whether a field is required.  Since  Reform::Form::ActiveModel::Validations did not delegate `validators_on` to the `Validator`. 
we can add   `delegates :validator, :validators_on` on 
https://github.com/apotonick/reform/blob/master/lib/reform/form/active_model/validations.rb#L24
or add this ability  to `Reform::Form::ActiveModel::ModelReflection`.
or add an initialize file as a workaround, waiting simple_form fix it  
```
Reform::Form.instance_eval do
  class << self
    delegates :validator, :validators_on
  end
end

```

**Comment by FelipeKoblinger** [comment]
Any idea how to make it work with Client Side Validations, @niedhui? I've tried those delegations and still nothing. But nested models are validating on Client Side Validations.

**Comment by niedhui** [comment]
@FelipeKoblinger  My solution is only for fixing the simple_form's label issuse, required mark.
I had  not used client-side-validations before, after a quick look at the source code, it add some methods to `ActiveModel::Validations`
https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_model.rb#L159
https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_model.rb#L26
the rest of the GEM seems to try test whether the model(form here) is respond to `client_side_validation_hash `, maybe add  `    delegates :validator, :validators_on, :client_side_validation_hash` to the initializer file  will work.
if not, you may need to figure out which methods is lost, example code below(I did not test it myself, just for showing what you can do ), after you find which methods is lost, add back using delegation. wish this helps
```ruby
Reform::Form.instance_eval do
  class << self
    def method_missing(methId, *args)
      if validator.respond_to? methId
        puts "Got a missing method #{methId}"
        validator.send(methId, *args)
      else
        super
      end
    end

    def respond_to?(methId, include_all = false)
      super || validator.respond_to?(methId, include_all) 
    end
  end
end

```

**Comment by FelipeKoblinger** [comment]
Hi, @niedhui!
Delegates didn't work. But the problem was in method `client_side_validation_hash` (thanks for the tip).
I made it work, but I think it isn't the best way (but worked lol). I added that method to initializer file:

```ruby
Reform::Form.class_eval do
  include Reform::Form::ActiveModel::Validations

  def client_side_validation_hash(force = nil)
    self.model.client_side_validation_hash(force)
  end
end
```

That along with your solution for Simple Form and now everything is working again :)

Thanks

**Comment by niedhui** [comment]
Oh I see, `client_side_validation_hash` is a instance method :smile:

**Comment by apotonick** [comment]
Please, open tickets on the respective gems and ask the authors to fix that against Reform. This is really important as this will drive the conversation to stable interfaces between forms, models and form renderers and probably brings this monkey-patching era to an end.

**Comment by nicolas-besnard** [comment]
This issue is still around. None of the mentioned monkey-patch is working. Does any of you have a new solution ?

**Comment by nicolas-besnard** [comment]
Seems like including `Reform::Form::ActiveModel::ModelReflections` in my form did the work

**Comment by SirRawlins** [comment]
Including the reflections worked for me too. Also had other positive impacts on the SimpleForm builder being able to auto-detect text vs textarea fields etc.

@apotonick any way to get this module included by default when people are using simple-form instead of manually including in every form object?
