### ISSUE TITLE
Reform 2.0 breaks ActiveRecord uniqueness validation

### ISSUE THREAD

**Issue by gertfj** [apotonick/reform#264]
The follwing code works with Reform 1.2.6 but fails in Reform 2.0.1 with the message: ArgumentError (Unknown validator: 'UniquenessValidator')

```ruby
validates :email, presence: true, uniqueness: { case_sensitive: false }
```

In Reform 2.0.1 I have to write the following:

```ruby
validates :email, presence: true
validates_uniqueness_of :email, case_sensitive: false
```

**Comment by apotonick** [comment]
http://trailblazerb.org/gems/reform/validation.html#uniqueness-validation

I will drop ActiveModel support soon, so please keep that in mind when opening tickets.

**Comment by gertfj** [comment]
Damn I'm sorry to hear that, Reform is the best Form object gem out there but I prefer working with the validations I've used for years.

Are you dropping it totally or allowing people to choose which validations they want to use?

**Comment by apotonick** [comment]
Sorry!! But I have to make decisions in order to keep moving, otherwise I will waste another 10 years of my life with fixing shit that should be fixed in Rails itself.

I am not sure if I will keep providing both as people will assume that I support ActiveModel, which I don't. Also, the new features like removing validations in subclasses, cascaded validations, etc. are impossible to implement with ActiveModel, so it's probably best to say "Good-bye!".

**Comment by apotonick** [comment]
BTW, you already put the most sensitive part of an app - validation - in the hands of Reform. Replacing rather primitive validations with another implementation is the part you should be the least worrying part! :stuck_out_tongue_winking_eye: :

**Comment by gertfj** [comment]
Yeah that's totally fair of course. I'll continue using 1.2.6 for now as there are too many breaking changes for now (which is also fair when you bump to a major new version) and reevaluate when I start the next project.
