### ISSUE TITLE
Reform marking Carrierwave fields as "changed" even when they're not

### ISSUE THREAD

**Issue by mipearson** [apotonick/reform#284]
Real test case pending - putting this here to see if anybody else has had this issue & can suggest a resolution before I try to get a proper reproduction together.

Since adding ReForm to our stack we found that certain previously fast API actions were taking nearly a second to complete.

Our form's properties include our Carrierwave mapped fields, as we let users add images via this form.

On investigation we discovered that calling `.validate(params)` on our form would mark those images as changed even if params did not include the image fields.

However, the images would be preserved - no change would actually occur - but carrierwave would spend the time processing & resizing the original image anyway.

**Comment by mipearson** [comment]
Investigation notes:

  * Removing the properties from the form object "fixes" the issue
  * Does not affect non-API calls - ie, when Carrierwave's hidden fields are populated, the carrierwave fields are not changed
  * Calling item.save! directly does not flag the fields as changed

So .. I suspect that Reform is iterating through the defined properties and doing .. something that carrierwave doesn't like. Carrierwave's AR integration is famously broken, so I suspect that Reform is performing the reasonable action of reading a property and then setting it to the same value, which is then confusing carrierwave, as carrierwave does very strange things in its getter/setter methods.

I don't like carrierwave very much.

**Comment by apotonick** [comment]
The problem is that CarrierWave is tying its logic to AR and since Reform goes the opposite way, saying _"remove all logic from AR because it sucks"_, this causes trouble.

The upload should not happen in the model scope at all. We successfully do this in chapter _Callbacks_ of the Trailblazer book where we use Paperdragon for the upload. Paperdragon doesn't use any AR features for the upload, it's all in your hands. On the other side, CarrierWave gets triggered by AR magic like the "changed" callbacks, which is wrong.

When you save "Reform marks fields as changed" do you mean the fields on the _model_ or the fields on the _form object_?

In both cases, we could try to prevent the image fields as being set as "changed". This will prevent CW to be run for empty uploads.

**Comment by apotonick** [comment]
BTW I think CarrierWave is great, the only problem I have with it is how it is coupled to AR and relies on AR features to work properly. That's why I wrote https://github.com/apotonick/paperdragon to "demonstrate" that you can achieve uploads without any AR coupling.

**Comment by mipearson** [comment]
I agree that the way that Carrierwave does things is not the right way. I think that Carrierwave's core is solid, but its AR integration is terrible. Too much DWIM.

Unfortunately removing the carrierwave bindings isn't in scope - it'd be a very big change for our project.

The fields are being marked as changed on the model. I tested this by adding a before_save hook to print out the contents of `.changes`.

This is now of lower priority for us - we've worked out that we didn't actually need the image fields on that form - we have a separate API endpoint for images. Removing them from the properties array "fixed" the problem for us.

**Comment by apotonick** [comment]
Sounds about right to me! Yeah, I wasn't trying to sell you Paperdragon (that would mean even more work for me), but it's just another example how you can do things explicitly with one more line of code instead of relying on AR's horrible callback mechanism that has made every Rails developer's life painful.

If you keep running into callback problems, I recommend you looking into Trailblazer for 10 minutes. It completely removes callbacks and validations from models and introduces a new abstraction layer called _Operation_ (use case). You will love it.

**Comment by mipearson** [comment]
Do you mind if this is left open? While no longer an issue for us, it will hopefully mean that if somebody else tries to cross these streams they'll see this open issue and go "oh, that doesn't work then".

**Comment by apotonick** [comment]
41 or 42 open issues, what's the difference haha?

**Comment by radar** [comment]
We just had another issue here where Reform was not passing attributes through to an AR model; it was the `remove_fn_large` attribute it wasn't passing through.

Fuck Carrierwave.

**Comment by apotonick** [comment]
Should we... try something like `reform-carrierwave` where we provide some better integration? We use Carrierwave here so I guess I can "allocate some time" haha. :laughing:

**Comment by mipearson** [comment]
I'd like to understand _why_ the attrs aren't being passed through, just in case we have this problem with another AR integration, or our own code. Getting reform working with carrierwave isn't a priority for us - we can use it as (another) lever to argue for removing carrierwave's AR integration from our codebase.

**Comment by apotonick** [comment]
@mipearson @radar Chat on IRC? Also, a sample appwould help me, I don't use CarrierWave and have no idea how to set it up. :sleeping:

**Comment by dnl** [comment]
they are being passed through.

It's just that Carrierwave, when told `file=File` and `remove_file="1"`, `file=File` will win.

Carrierwave expects that the form will tell it `file=''` if the file is to remain unchanged.
```
def #{uploader}=(value)
  super(value.is_a?(CarrierWave::Uploader::Base) ? nil : value)
end
```

**Comment by bramj** [comment]
In case of anyone else getting bitten by this (especially with Carrierwave uploads), adding `include Sync::SkipUnchanged` to the form object seems to do the trick.

Found here:  http://trailblazer.to/gems/reform/#dirty-tracker

**Comment by fran-worley** [comment]
Thanks @bramj I'm going to close this now as it's gone pretty stale and your solution looks sensible.
