### ISSUE TITLE
:test property doesn't work when performing validation

### ISSUE THREAD

**Issue by Azdaroth** [apotonick/reform#285]
`:test` property doesn't work when performing validation, steps to reproduce issue:

```
SomeModel = Struct.new(:test)

class SomeForm < Reform::Form
  property :test, validates: { presence: true }
end

SomeForm.new(SomeModel.new).validate(test: true)

=> ArgumentError: wrong number of arguments (0 for 2..3)
```

Stacktrace leads here: https://github.com/rails/rails/blob/v4.1.8/activemodel/lib/active_model/validator.rb#L165

It was kinda a mystery how it could cause ArgumentError, but for some reason the `record` must be nil, because:

```
nil.send(:test)
ArgumentError: wrong number of arguments (0 for 2..3)
```

I have no idea for now why it happens so only with `:test` property, maybe some voodoo with ActiveSupport callbacks somewhere. It works on Reform 1.2.x though.

**Comment by apotonick** [comment]
Is that only for `#test` in particular or all property names?

Please do `SomeForm.new(..).test` and `SomeModel.new.test` and tell me what happens.

**Comment by Azdaroth** [comment]
It happens only for `test` property name.

Writing and reading attributes works fine:

```
SomeModel.new.test => nil
form = SomeForm.new(SomeModel.new)
form.test => nil
form.test = true
form.test => true
```

it just happens when performing validation.

**Comment by apotonick** [comment]
I looked into it and it comes from `#read_attribute_for_validation` which is somehow overwritten, but only for `test` somewhere in ActiveModel. So, basically, if you do `form.read_attribute_for_validation(:test)` you will get this error.

Since I decided to drop support for ActiveModel with Reform 2.x (because of "features" like this) I won't look into it further. The new, better, cleaner and more awesome validations with Lotus should be stable in a few weeks and then nobody will ever want to go back to AM anyway, so please rename it and have some more days of patience. :heart:

**Comment by Azdaroth** [comment]
Yeah, already renamed it, the AM does some hardcore voodoo here, still no idea how it got overwritten for `test` property :stuck_out_tongue: 

Can't wait for validatons without any black magic :beer:

**Comment by apotonick** [comment]
And this: https://github.com/apotonick/reform/wiki/Rich-Validations
