### ISSUE TITLE
Default value is not applied in case of empty string

### ISSUE THREAD

**Issue by dragosmiron** [apotonick/reform#299]
eg
`property amount, type: BigDecimal, default: BigDecimal(0)`
if `amount` is 1 or "1" then when I perform the `validate` i get it converted to `BigDecimal(1)`
but if `amount` is `""` then it remains as `""` after validation.

Is this expected or a bug?

**Comment by fran-worley** [comment]
@dragosmiron Default is only applied when a value is actually `nil?`. Given that an empty string is in fact not `nil?` your default won't get set.

So to answer your question it is expected. What you could do is set the value in prepopulate! or override the setter to use your default when an empty string or nil. Alternatively, you could make use of the new nilify option http://trailblazer.to/gems/disposable/api.html#nilify to ensure that you always have nils instead of empty strings.

**Comment by fran-worley** [comment]
As this isn't an issue with Reform I'm going to close. Feel free to catch us on the Trailblazer gitter channel if you've got any other queries 😸
