### ISSUE TITLE
Model validations not being copied to form object

### ISSUE THREAD

**Issue by kevinbrink** [apotonick/reform#302]
I'm having an issue getting reform to automatically copy validations from the model to the form object. I'll admit I'm a newbie when it comes to Reform (and only slightly less of one with rails in general), but I believe I'm setting things up correctly, and the validations on the form object just.. Don't trigger. 

The entire code base is a little more complex, obviously, but here's the basic setup of what I'm trying to do:
```
class Person < ActiveRecord::Base
  include ActiveModel::Model
  # Person has a dob property that needs to be validated
  validate :dob_valid

  private

  def dob_valid
    # Return if the dob is considered valid
    return if dob.blank? || TimeDifference.between(Date.current, dob).in_years >= 18
    # Invalid!
    errors.add :dob, 'has to be at least 18 years ago'
  end
end
```

```
class PersonForm < Reform::Form
  extend ActiveModel::ModelValidations
  copy_validations_from Person
  property :dob
end
```

```
class PersonController < ApplicationController
  before_action :init_person, only: [:new, :create]

  def new
    respond_with @person_form
  end

  def create
    if @person_form.validate params[:person]
      @person_form.save
      respond_with @person_form
    else
      render 'new'
    end
  end

  private

  def init_person
    @person = Person.find(session[:id])
    @person_form = PersonFrom.new @person
  end
end
```

First question: Should this work? Do I have some glaring logic error that I've missed in regards to copying validations from the model? The only difference that I could see from my code to the example code is that my model inherits from `ActiveRecord::Base`, which I hope wouldn't affect it. 

The problem is that the @person_form always passes the validation. After I call `@person_form.save`, I can check `@person_form.model.errors`, and see the errors that I expect when I submit bad data, but those errors are never shown in the `@person_form` object, even after a call to `validate` and `prepopulate` (which I thought may copy over errors, but doesn't appear to). 

The validations run as expected when I manually copy them over to the reform object, but obviously that's not desirable. 

Any ideas and / or tips are appreciated!

**Comment by apotonick** [comment]
Hi Kevin,

I'm sorry to tell you that I do not support this feature anymore and will soon drop it. 

Don't get me wrong, I would _love_ to help you on this. However, copying "validations" is terribly messy and when it comes to scopes and invocation contexts, it becomes unmanageable.

I could now spend a lot of time trying to hack this and make it possible to "copy" custom validations. Or, and that's what I decided to do, is tell people to 
* not have validations in their models
* never use models directly (because it's a low-level persistence entity and not a high-level domain object)
* encapsulate form/model interaction into a service object

In Trailblazer, this happens in an operation, which is what you might be interested in.

As a work-around for you, I recommend to physically copy the validation code (so you really feel the pain hahahaha). Sorry again, and let me know if I can help you in any other way. :beers:

**Comment by apotonick** [comment]
To explain what's happening in your case:

1. Reform copies the declarative validation from your model class to itself.
2. When validating, it sees this declaration and invokes the custom method _on the model_.
3. The model now marks its `errors` as invalid.
4. The form, whatsoever, still has a clean `errors` and thinks its valid.

Does that make it clear? Thanks for your lightweight report, was very understandable since you stripped out unnecessary noise.

**Comment by kevinbrink** [comment]
Ah, that does make sense; so the validations are being run, but only on a model level, so the errors aren't added to the form object. 

I had assumed the validations would be run on the form object itself. 

Thanks for your clear reply, and your great work on this stuff!

**Comment by apotonick** [comment]
The tricky part is: the "formal" validations like `presence: true` are run on the form object, but custom ones require `ActiveModel::Validations` to delegate to the custom method, and that's where it becomes messy. Thanks!

**Comment by apotonick** [comment]
Oh, and don't misread that as "you can't have custom validations in Reform"! :grimacing: You can, but not when using `copy_validations_from` which I discourage using anyway.

**Comment by kevinbrink** [comment]
Yeah, I think I follow; to have custom validations on the form object, you'd have to define them explicitly in the form object itself, as opposed to automatically copying it from the model. 

Thanks for your help! Really appreciate it!

**Comment by AnwarShah** [comment]
Hi! First thanks for this helpful issue. I'm trying to use Reform. I too have a numericality validation on the model with a custom method. How should I move this method to FormObject? The validation is like this

```
validates :mark_given, numericality: { less_than_or_equal_to: :allowed_max_mark }
```

The `#allowed_max_mark` is defined on the mark model. Should I leave it there or move it on form object? I tried using `delegate` and it works, but I didn't like this approach. Also, I am planning to use another form object based on the same model and that should have this same validation. So, I fear duplication of code.

**Comment by apotonick** [comment]
Move the method to a shareable form module: http://trailblazer.to/gems/reform/api.html#forms-in-modules :wink:
