### ISSUE TITLE
collections with :skip_if filled with nil, raises exception on validate

### ISSUE THREAD

**Issue by akamike** [apotonick/reform#313]
A collection using `skip_if` becomes filled with `nil` when skipped items are before non-skipped items, due to retaining the original indexes. While that particular setup seems to be the responsibility of [Representable](https://github.com/apotonick/representable), it can cause issues in reform - it shouldn't be trying to call `validate!` on `nil`.

This is not caught by the [tests](https://github.com/apotonick/reform/blob/master/test/skip_if_test.rb#L43) because it only tests for skipped items at the end of the input. My expectation would be for the following addition to pass (it currently does not):

````ruby
# additions to test/skip_if_test.rb
class SkipIfTest < BaseTest
  # ...

  # skips deserialization when not present, regardless of position
  it do
    form = AlbumForm.new(Album.new(nil, nil, []))
    form.validate("songs" => [
      {"title" => nil},
      {"title" => "Altar Of Sacrifice"},
      {"title" => nil},
      {"title" => "Waste Of Breath"},
      {"title" => nil},
      {"title" => "Fear of a Blank Planet"},
      {"title" => nil}
    ]).must_equal true
    form.songs.size.must_equal 3
    form.songs[0].title.must_equal "Altar Of Sacrifice"
    form.songs[1].title.must_equal "Waste Of Breath"
    form.songs[2].title.must_equal "Fear of a Blank Planet"
  end
end
````

The fix for this is to reset the indexes on the collection, since just handling this in validate causes issues with the returned collection. However, I noticed a few other tests that seem to rely on this behaviour:

* https://github.com/apotonick/reform/blob/master/test/deprecation_test.rb#L24
* https://github.com/apotonick/reform/blob/master/test/---populator_test.rb#L23
* https://github.com/apotonick/reform/blob/master/test/populate_test.rb#L199 (this is [present on 2.0.5](https://github.com/apotonick/reform/blob/v2.0.5/test/populate_test.rb#L190))

Raising this as an issue to help clarify what is the expected behaviour, and perhaps look at ways to accomplish my provided test case. `deprecation_test.rb` and `---populator_test.rb` seem to offer a workaround for the validation part, but this feels hacky and incomplete.

**Comment by kevinbrink** [comment]
I believe this is the exact same issue I've been struggling with for the past few days. 

As a side note, I'm also using [cocoon](https://github.com/nathanvda/cocoon), but I don't think that's causing any issues. 

Basically, I was getting a `NoMethodError: undefined method validate! for nil:NilClass` whenever I tried to update after both removing and adding an item of a collection in a single action. 

I did a *lot* of digging, and I think I've figured out *a* fix for it; I'm just not sure what else it might affect. Seems to work so far for my use cases though:

Inside the Reform gem (version 2.0.5), in `lib/reform/form/populator.rb`, line 53, change it from this:

`twin.insert(index, run!(form, fragment, options)) # form.songs.insert(Song.new)`

To this:

`twin.insert([index, twin.count].min, run!(form, fragment, options)) # form.songs.insert(Song.new)`

Without this, the `index` would be set to a number greater than the last index of non-deleted collection items, causing the item to be inserted past that last index, meaning that the `twin` array ended up looking something like this after this line of code executed:
```
twin = [
  ValidCollectionItem,
  nil,
  ValidCollectionItem
]
```

Which is why it blows up when other code iterates through the collection and tries to validate each one of them. 

@apotonick , I'll try to get up a pull request sometime tomorrow for this fix, but until then, let me know if you think this is a good fix. 

I noticed that this github repo seems to be on a later version than `2.0.5` (something like `2.1.pre1`, if I remember right), and I did try to test it quickly to see if it fixed this bug, but it seemed to break some other things, so I'll admit I didn't spend much time on it.

**Comment by apotonick** [comment]
Always test against `reform/master`, it is incredibly important for me to get early feedback.

I'll get back to that as soon as I can, I want to get Reform 2.1 out the door (which introduces `skip!` in populators, so you don't need to use `:skip_if` anymore.

**Comment by kevinbrink** [comment]
Thanks for the reply @apotonick!

Just to make sure, you mean you want me to pull your master, make my changes, and then ensure running `rake test` completes successfully?

I may be able to do that at some point, but I'm still using `version 2.0.5`, and your latest changes seem to break some things for the app I'm working on. I'm not sure when I'll have time to update the application to work with your latest changes. 

I did fork your repo and reverted back to `version 2.0.5`, made my changes, and ran a `rake test`. It didn't have any failures, but it had 2 skips; is that expected? 

Let me know how you want me to proceed. It makes sense that you want to get version 2.1 out, but I may end up just using my own version of 2.0.5 temporarily, until I can work my app into your 2.1 version.

**Comment by apotonick** [comment]
Thanks @kevinbrink: https://github.com/apotonick/reform/commit/c7a1bc247cf66c95ef2c269f77f2bb5f32470170

**Comment by kevinbrink** [comment]
No problem @apotonick! Thanks for your work on this!
