### ISSUE TITLE
Json in Form

### ISSUE THREAD

**Issue by abmahmoodi** [apotonick/reform#326]
Hi,
In Rails 4.2.4 I have a form like this:
```ruby
class UserJsonForm < Reform::Form
  include Reform::Form::JSON
  
  model 'tipax/user'

  property :email
end

```
but in the rails console when I run this code:
```ruby
u=UserJsonForm.new(Tipax::User.new) 
u.validate('{"email":"msd@usa.com"}')
```
this error raised:
undefined method `has_key?' for "{\"email\":\"msd@usa.com\"}":String
from /home/abmahmoodi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/reform-2.0.5/lib/reform/form/active_model/form_builder_methods.rb:39:in `rename_nested_param_for!'

hash param is OK.

**Comment by apotonick** [comment]
The `JSON` module doesn't exist, you must have picked that up from an old blog post. Here are examples how that could work: https://github.com/apotonick/reform/blob/430b70e5b886a01858fa78189b6b3dff4fe653ed/test/deserialize_test.rb#L17

However, I advise you to check out the *Hypermedia APIs: Deserialization* chapter of the Trailblazer book which discusses this, and I also recommend using Trailblazer instead of a bare form for this task as you will need a representer _and_ a form and that's what the operation does for you! :beers:
