### ISSUE TITLE
Name of a certain form gets changed each time when referenced from property

### ISSUE THREAD

**Issue by tscholz** [apotonick/reform#353]
Hi,

thanks for this nice gem.

Unfortunately, I'm running into trouble when using a form for a property or collection inside another form:

```
class OwnerForm < Reform::Form

  def magic_calculator
      MagicCalculator.new #actually OwnerForm::MagicCalculator, it's nested
  end
end

OwnerForm.name #=> OwnerForm

class ProjectForm < Reform::Form
  property :template_owner, form: OwnerForm
end

OwnerForm.name #=> TemplateOwner ...should be OwnerForm

class OtherForm < Reform::Form
  collection :many_owners, form: OwnerForm
end

OwnerForm.name #=> ManyOwner  ...should be OwnerForm, but is changed again
```

In our project we have some helper/service classes defined like 'OwnerForm::MagicCalculator` used for (pre)-population:

```
forms/owner_form/magic_calculator.rb
forms/owner_form.rb
```

In Rails development environment for instance it can't lazy-load the `MagicCalculator` because it tries to load something like `ManyOwner` first. But for sure, a model or form with that name doesn't exist.

I'm currently work around this issue by loading inner classes using `require_dependency` inside e.g. the OwnerForm, but I'm not sure if this is the way to go? I think the name of the OwnerForm class should not change, shouldn't it?

**Comment by apotonick** [comment]
It's a problem with the brain-dead way ActiveModel computes and infers names from classes (not objects). As a work-around, we have to change the nested form's `name` here: https://github.com/apotonick/reform/blob/master/lib/reform/form/active_model.rb#L31

You can try to hack this hack, but I'm not interested in supporting much of ActiveModel anymore, since I think most of it is absolute rubbish. I will soon release Formular, and Reform with dry-validations, so there's no need for any AM anymore (happy days!!!).

For example, you could prevent this hack if `:form` is passed to property. If you come on the Gitter channel, I can help you.

**Comment by tscholz** [comment]
Thank you very much for your quick response. 

I'm about to integrate reform into our project that relies heavily on ActiveModel. I'm concerned about the fact that you are planning to drop ActiveModel support as it sounds like another refactoring I'd have to do in the near future, e.g. when upgrading to Rails 5. Unfortunately, this would cause me a lot of trouble. I would be very happy, if you think about the decision again - maybe to move the support to reform-rails, but please don't drop it at all.

Concerning the problem described above, for now it's working with the mentioned workaround. I'll finish the integration of reform into our project and see, if more problems occur. Apart from that, reform is working great so far. :)

I'm not quite sure what you mean with passing :form to ::property. We do that but the name of the passed form is changed to the name of the property and this is killing Rails dependency lookup inside the passed form in development environment. I think it should work somehow like associations in AR where I can pass the class name (same as :form?) if association name and associated class name differ, shouldn't it?

**Comment by apotonick** [comment]
Don't you worry, I will not simply "drop" support for AM, I will make it as painless as possible. However, you have to understand that I want to move on with my ideas and I've really wasted enough time trying to make my things work with Rails, and it is simply not what I would consider a good code design. Since I can't see anything changing in Rails, for me as a framework developer it's best to simply leave this sinking ship to itself and work with better, more intuitive alternatives.

Have you tried using the `:name` option to set a name statically for a nested form? :beers:

**Comment by fran-worley** [comment]
@tscholz all ActiveModel logic has moved to the reform-rails gem. Any update on the `:name` option suggestion?

I'm going to close this for now but please reopen/ raise an issue in reform-rails if you need 😄
