### ISSUE TITLE
Prefill form before validate

### ISSUE THREAD

**Issue by nibygro** [apotonick/reform#373]
Hi. I have a `Reform` form for the `User` model and the next business logic: application user write `first_name` and `last_name` to the view form, and when it is saved, these data should be united and saved to the `full_name` column.  Is there any before callbacks or something similar in the Reform ?

```ruby
class CreateForm < Reform::Form
   property :first_name
   property :last_name

   # How to call setup_full_name before validations ???

   validate :uniqueness

   def setup_full_name
      model.full_name = [first_name, last_name].join(', ')
   end

   def uniqueness
      errors.add(:base, 'Taken') if User.where(full_name: model.full_name).exists?
   end
end
```

**Comment by apotonick** [comment]
Have you seen this? trailblazer.to/gems/reform/prepopulator.html

**Comment by nibygro** [comment]
@apotonick  Yes, but I do not really understand how to use prepopulator

**Comment by apotonick** [comment]
Have you had a peek into the Trailblazer book? We explain prepopulators there in great detail. Come here: https://gitter.im/trailblazer/chat

**Comment by nibygro** [comment]
@apotonick no, I have not get a copy of the book.

I found that I can use `populator` option like that:

```ruby
   property :last_name, populator: -> (options) do
       self.last_name = options[:fragment]
       model.full_name = [first_name, last_name].join(', ')
   end
```

But it seems to bit a little tricky to me, what do you think?

**Comment by yjukaku** [comment]
@nibygro You should be using prepopulators.  Yes, you have to call `prepopulate!` manually (probably in your controller, after creating the Reform instance)

**Comment by apotonick** [comment]
It's not correct,  you need to use `:prepopulator` - see above!

**Comment by yjukaku** [comment]
@apotonick As far as I understand, isn't `prepopulator` for rendering the form? The title of the issue is worded a little confusingly - he's not trying to "Prefill the form", but more like trying to use what in ActiveModel would be a `before_validate` to change data after it comes from the form - sounds like what `populate` does? I'm just learning reform now so I may be wrong.

**Comment by apotonick** [comment]
Ok, then a populator is correct, but not the way @nibygro does it. The populator should *never* access the model. I would do that kind of mapping in the surrounding `Operation`. Note that Reform is **not a data mapper**. I was thinking of providing such behavior in a less clumsy way, though.

**Comment by fran-worley** [comment]
@nibygro if I understand you correctly you capture & validate first and last name then if valid persist the two fields as one column.

If that's the case, why don't you make a method to join the two and call it after validation but before sync/save ?

**Comment by yjukaku** [comment]
@nibygro @fran-worley As far as I can tell, that does seem like the correct method. 👍  `reform` is not designed for writing your attributes for you (other than the simple attribute assignment on`sync/save` that is really just a convenience)

**Comment by apotonick** [comment]
Yes, Reform is a form object and not a data mapper, and that's a good thing.

The `sync/save` is absolutely *not* convenience, though, but highly necessary to get the validated data back to your model(s). :grimacing:  BTW, if you're interested in the data mapping part, you should look into [twins](trailblazer.to/gems/disposable/) because they are data mappers (and Reform is based on twins)!!!
